version: 0.2

phases:
    pre_build:
        commands:
            - echo "prebuild"
    
    build:
        commands:
            - echo "...."
    
    post_build:
        commands:
            - echo "post_build"
